server:
  port: 8085


spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: java7
    password: root

  mail:
    #sunucu olarak kullanıcak mail burada yazılmalıdır.
    #yani kayıt olurken girilen mail' e aktivasyon kodu gönderecek ana mail burada yazılır
    username: bilgeadamum@gmail.com
    #google account manager altında 'uygulama şifreleri' üzerinden üretilen şifredir
    password: cllevpjbtavwgncm #${emailpassword}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  registerMailQueue: mail-queue