server:
  port: 7090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yemekTarifi
      username: YemekTarifiUser
      password: root
  rabbitmq:
    host: localhost
    port: 15672
    username: java7
    password: root
jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

rabbitmq:
  queueRegister: register-queue
  exchange: user-exchange
  queueElasticRegister: elastic-register-queue
  elasticRegisterBindingKey: register-key
  queueCreateRecipe: queue-recipe