server:
  port: 9099

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yemektarifi
    username: postgres
    password: U.m123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 15672
    username: java7
    password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

rabbitmq:
  exchange-auth: auth-exchange
  registerKey: register-key
  queueRegister: register-queue
  registerMailQueue: mail-queue
  registerMailBindingKey: mail-key
  #cllevpjbtavwgncm