server:
  port: 7080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yemekTarifi
      username: YemekTarifiUser
      password: root
  rabbitmq:
    host: localhost
    port: 15672
    username: java7
    password: root

rabbitmq:
  exchange: exchange
  queueCreatePost: queue-post
  bindingKeyCreatePost: binding-post