server:
  port: 80 #localhost <=> 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9099 #localhost:8090/api/v1/auth/find-all
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/auth-service

        - id: user-profile-service
          predicates:
            - Path=/user-profile/**
          uri: http://localhost:7090
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/user-profile-service
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}